### ISSUE TITLE
Double query execution for relation

### ISSUE THREAD

**Issue by mrrooijen** [GeorgeKaraszi/ActiveRecordExtended#44]
Thanks for the library.

The following code results in the execution of the two queries specified below.

```ruby
def set_post
  owned_posts  = current_user.posts
  shared_posts = current_user.shared_posts

  @post =
    Post
      .union(owned_posts, shared_posts)
      .find_by(id: params[:id])
end
```

```sql
SELECT "posts".* FROM "posts" WHERE "posts"."user_id" = $1  [["user_id", "91b027c3-3d08-4520-a6ee-a7498c90bcff"]]

SELECT "posts".* FROM (( (SELECT "posts".* FROM "posts" WHERE "posts"."user_id" = '91b027c3-3d08-4520-a6ee-a7498c90bcff') UNION (SELECT "posts".* FROM "posts" INNER JOIN "collaborations" ON "posts"."id" = "collaborations"."post_id" WHERE "collaborations"."user_id" = '91b027c3-3d08-4520-a6ee-a7498c90bcff') )) posts WHERE "posts"."id" = $1 LIMIT $2  [["id", "6a3df22b-082e-4d83-87d0-b5c92fc3cc87"], ["LIMIT", 1]]
```

It appears that whenever I pass one of the two objects (owned_posts or shared_posts) into the first argument of the `union` method, it'll execute that query prior to executing the proper UNION query.

I found a way around it by converting the queries to SQL strings before to passing them to the `union` method:

```ruby
def set_post
  owned_posts  = current_user.posts.to_sql        # necessary to avoid additional query
  shared_posts = current_user.shared_posts.to_sql # unnecessary, but works

  @post =
    Post
      .union(owned_posts, shared_posts)
      .find_by(id: params[:id])
end
```

This results in just a single query:

```sql
SELECT "posts".* FROM (( (SELECT "posts".* FROM "posts" WHERE "posts"."user_id" = '4a295157-2786-4508-bc6c-cb9aecaafd8b') UNION (SELECT "posts".* FROM "posts" INNER JOIN "collaborations" ON "posts"."id" = "collaborations"."post_id" WHERE "collaborations"."user_id" = '4a295157-2786-4508-bc6c-cb9aecaafd8b') )) posts WHERE "posts"."id" = $1 LIMIT $2  [["id", "6a3df22b-082e-4d83-87d0-b5c92fc3cc87"], ["LIMIT", 1]]
```

Is there a reason why I can't just pass in `current_user.posts` instead of `current_user.posts.to_sql`? Is it acceptable to call `.to_sql`  prior to passing it into the `union` method?

Thanks!

**Comment by itay-grudev** [comment]
I just stumbled upon the same issue. I additionally used  `gem 'active_record_query_trace'` to get a backtrace of where it's triggered from. I'll post an excerpt from `activerecord_extended` as well as full backtrace in the hope it's useful in identifying the issue.

Also please note that this is a <span style="color:red">**serious**</span> performance issue!

#### Excerpt

```txt
/home/user/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/active_record_extended-2.0.0/lib/active_record_extended/query_methods/unionize.rb:110:in `union'/home/user/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/active_record_extended-2.0.0/lib/active_record_extended/active_record/relation_patch.rb:11:in `union'
```

#### Full backtrace

```txt
Query Trace:
      /home/user/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/active_record_query_trace-1.8/lib/active_record_query_trace.rb:105:in `fully_formatted_trace'
      /home/user/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/active_record_query_trace-1.8/lib/active_record_query_trace.rb:66:in `sql'
      /home/user/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/activesupport-6.1.2.1/lib/active_support/subscriber.rb:150:in `finish'
      /home/user/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/activesupport-6.1.2.1/lib/active_support/log_subscriber.rb:115:in `finish'
      /home/user/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/activesupport-6.1.2.1/lib/active_support/notifications/fanout.rb:157:in `finish'
      /home/user/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/activesupport-6.1.2.1/lib/active_support/notifications/fanout.rb:63:in `block in finish'
      /home/user/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/activesupport-6.1.2.1/lib/active_support/notifications/fanout.rb:63:in `each'
      /home/user/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/activesupport-6.1.2.1/lib/active_support/notifications/fanout.rb:63:in `finish'
      /home/user/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/activesupport-6.1.2.1/lib/active_support/notifications/instrumenter.rb:45:in `finish_with_state'
      /home/user/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/activesupport-6.1.2.1/lib/active_support/notifications/instrumenter.rb:30:in `instrument'
      /home/user/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/sentry-rails-4.3.4/lib/sentry/rails/tracing.rb:41:in `instrument'
      /home/user/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/activerecord-6.1.2.1/lib/active_record/connection_adapters/abstract_adapter.rb:687:in `log'
      /home/user/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/activerecord-6.1.2.1/lib/active_record/connection_adapters/postgresql_adapter.rb:674:in `exec_no_cache'
      /home/user/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/activerecord-6.1.2.1/lib/active_record/connection_adapters/postgresql_adapter.rb:653:in `execute_and_clear'
      /home/user/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/activerecord-6.1.2.1/lib/active_record/connection_adapters/postgresql/database_statements.rb:53:in `exec_query'
      /home/user/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/activerecord-6.1.2.1/lib/active_record/connection_adapters/abstract/database_statements.rb:532:in `select'
      /home/user/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/activerecord-6.1.2.1/lib/active_record/connection_adapters/abstract/database_statements.rb:69:in `select_all'
      /home/user/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/activerecord-6.1.2.1/lib/active_record/connection_adapters/abstract/query_cache.rb:101:in `block in select_all'
      /home/user/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/activerecord-6.1.2.1/lib/active_record/connection_adapters/abstract/query_cache.rb:118:in `block in cache_sql'
      /home/user/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/activesupport-6.1.2.1/lib/active_support/concurrency/load_interlock_aware_monuserr.rb:26:in `block (2 levels) in synchronize'
      /home/user/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/activesupport-6.1.2.1/lib/active_support/concurrency/load_interlock_aware_monuserr.rb:25:in `handle_interrupt'
      /home/user/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/activesupport-6.1.2.1/lib/active_support/concurrency/load_interlock_aware_monuserr.rb:25:in `block in synchronize'
      /home/user/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/activesupport-6.1.2.1/lib/active_support/concurrency/load_interlock_aware_monuserr.rb:21:in `handle_interrupt'
      /home/user/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/activesupport-6.1.2.1/lib/active_support/concurrency/load_interlock_aware_monuserr.rb:21:in `synchronize'
      /home/user/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/activerecord-6.1.2.1/lib/active_record/connection_adapters/abstract/query_cache.rb:109:in `cache_sql'
      /home/user/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/activerecord-6.1.2.1/lib/active_record/connection_adapters/abstract/query_cache.rb:101:in `select_all'
      /home/user/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/activerecord-6.1.2.1/lib/active_record/querying.rb:47:in `find_by_sql'
      /home/user/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/activerecord-6.1.2.1/lib/active_record/relation.rb:850:in `block in exec_queries'
      /home/user/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/activerecord-6.1.2.1/lib/active_record/relation.rb:868:in `skip_query_cache_if_necessary'
      /home/user/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/activerecord-6.1.2.1/lib/active_record/relation.rb:835:in `exec_queries'
      /home/user/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/activerecord-6.1.2.1/lib/active_record/association_relation.rb:54:in `exec_queries'
      /home/user/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/activerecord-6.1.2.1/lib/active_record/relation.rb:638:in `load'
      /home/user/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/activerecord-6.1.2.1/lib/active_record/relation.rb:249:in `records'
      /home/user/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/activerecord-6.1.2.1/lib/active_record/association_relation.rb:15:in `=='
      /home/user/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/active_record_extended-2.0.0/lib/active_record_extended/query_methods/unionize.rb:110:in `union'
      /home/user/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/active_record_extended-2.0.0/lib/active_record_extended/active_record/relation_patch.rb:11:in `union'
```
